const items = {
  mobiles: [
    {
      name: "Samsung Galaxy f13",
      description: "( copper 128Gb)",
      img: "\\items\\mobiles\\samsungF13.webp",
      price: 11999,
      orgprice: 16999,
      offpercent: "29%off",
    },
    {
      name: "Samsung Galaxy f23",
      description: "(Aqua blue 128Gb)",
      img: "\\items\\mobiles\\samsungF23.webp",
      price: 11999,
      orgprice: 16999,
      offpercent: "29%off",
    },
    {
      name: "Samsung Galaxy A13",
      description: "(midnigt blue 64Gb)",
      img: "\\items\\mobiles\\samsungA13.webp",
      price: 10500,
      orgprice: 14999,
      offpercent: "29%off",
    },
    {
      name: "Redmi 10",
      description: "(midnight black 64Gb)",
      img: "\\items\\mobiles\\redmi10.webp",
      price: 10999,
      orgprice: 14999,
      offpercent: "29%off",
    },
    {
      name: "Apple iphone 13",
      description: "(Pink 128Gb)",
      img: "\\items\\mobiles\\Apple13pink.webp",
      price: 61999,
      orgprice: 69999,
      offpercent: "29%off",
    },
    {
      name: "Apple iphone 13",
      description: "(black 128Gb)",
      img: "\\items\\mobiles\\Apple13.webp",
      price: 61999,
      orgprice: 69999,
      offpercent: "29%off",
    },
    {
      name: "Samsung Galaxy f13",
      description: "( copper 128Gb)",
      img: "\\items\\mobiles\\samsungF13.webp",
      price: 11999,
      orgprice: 16999,
      offpercent: "29%off",
    },
    {
      name: "Samsung Galaxy f23",
      description: "(Aqua blue 128Gb)",
      img: "\\items\\mobiles\\samsungF23.webp",
      price: 11999,
      orgprice: 16999,
      offpercent: "29%off",
    },
    {
      name: "Samsung Galaxy A13",
      description: "(midnigt blue 64Gb)",
      img: "\\items\\mobiles\\samsungA13.webp",
      price: 10500,
      orgprice: 14999,
      offpercent: "29%off",
    },
    {
      name: "Redmi 10",
      description: "(midnight black 64Gb)",
      img: "\\items\\mobiles\\redmi10.webp",
      price: 10999,
      orgprice: 14999,
      offpercent: "29%off",
    },
    {
      name: "Apple iphone 13",
      description: "(Pink 128Gb)",
      img: "\\items\\mobiles\\Apple13pink.webp",
      price: 61999,
      orgprice: 69999,
      offpercent: "29%off",
    },
    {
      name: "Apple iphone 13",
      description: "(black 128Gb)",
      img: "\\items\\mobiles\\Apple13.webp",
      price: 61999,
      orgprice: 69999,
      offpercent: "29%off",
    },
  ],
};

export const { mobiles } = items;
